// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myayrzbptbldtthelylh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15YXlyemJwdGJsZHR0aGVseWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzQyOTUsImV4cCI6MjA3MDc1MDI5NX0.Ad-QrFxuU0WqDpyRTcDXpKaNf9SGULAjQRSm6ooaJdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});